apiVersion: v1
kind: Pod
metadata:
  name: pod11-10
spec:
  containers:
  - image: damrongsak/d8k-app:start40s
    name: pod11-10
    readinessProbe:
       httpGet:
         path: /healthz
         port: 4000

