apiVersion: v1
kind: Pod
metadata:
  name: pod15
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sh","-c", "echo $SERVER"]
      imagePullPolicy: IfNotPresent
      env:
        - name: SERVER
          valueFrom:
            secretKeyRef:
              name: secret-app-info
              key: server

