apiVersion: v1
kind: Pod
metadata:
  name: pod11-7
spec:
  containers:
  - image: damrongsak/hello:8080
    name: hello8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80

