apiVersion: v1
kind: Pod
metadata:
  name: pod11-6
spec:
  containers:
  - image: damrongsak/hello:8080
    name: hello8080
  initContainers:
  - image: busybox
    name: bbox
    command: ["/bin/sh", "-c", "sleep 6000"]
  restartPolicy: Never

