apiVersion: v1
kind: Pod
metadata:
   name: pod6
spec:
  containers:
    - name: container6
      image: centos:8
      command:
        - "sh"
        - "-c"
        - "while true; do echo \"log [at] \"`date`; sleep 7; done"
      imagePullPolicy: IfNotPresent

