apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-deny-egress
  namespace: production
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
     - protocol: UDP
       port: 53

