apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data12
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mystorage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/student0/storage12
    server: nfs.d8k.io
