apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-more
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: mystorage

