apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app
  name: server1
spec:
  hostname: server1
  subdomain: app
  containers:
  - image: damrongsak/hello:8080
    name: server1
    imagePullPolicy: IfNotPresent

