apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user1
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQm1UQ0NBUUlDQVFBd1dURUxNQWtHQTFVRUJoTUNWRWd4RERBS0JnTlZCQWdNQTBKTFN6RU1NQW9HQTFVRQpCd3dEUWt0TE1SRXdEd1lEVlFRS0RBaFRaV04xY21sMGVURUxNQWtHQTFVRUN3d0NTVlF4RGpBTUJnTlZCQU1NCkJYVnpaWEl4TUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDMnlHa1VOUVp6MkJVc2YraTkKZFUvOHZtYVN5czlpSXpTSnVCeVJCYnVIN1FkdnRjT285OXRZbzJrZkY1Z0NLNE1HNHYyallhMnFKYlhyN0o3dgpaWU9CMWpKdTVNM2dNZzRpejFUVWJOa2EzMERGdkliME9yNWorREJkcU1Tbi9YNkF2bk1IRUJvZmVrRFk3ZlAvCkZzNU1OY1U5QlZxeGZpNGlqNWxTaHAwZ2VRSURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ1lFQVIyNzkKdmovRlZFVjhTRVFpZXgwZWR3VFBYWm0ydDZDcGFNRS92U0RwSC9IRTJDWHNobmJWREVmNUorTGZFZVp4bXdWRgpGWlNHOHIvMWtUZjVyL1pkQ0tFZHBxRTNYbkRPc05jMG4wc3A5TENXWU5JZVgrL1J0dnU4b0tRRlkrWGlURXU1ClRDKzE0MmdlRzRQZVV2a0lPUXF1cHUzTTlSdGhwN1k3ZUhwWk1Raz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
